name = "Fabric Modpack 1.18.2"
author = "Laen111"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff83931e25cec01bf24a277e84074d05392f9b174563783069a548a318abbc1"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
