name = "Fabric Modpack 1.18.2"
author = "Laen111"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b213664aabdd0406708783958e5337c0ab359f975af15f78bb7c0a7441c7171b"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2"]
