name = "Fabric Modpack 1.19"
author = "Laen111"
version = "1.7.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b86bb6f355ebd2d614da119853b42f86311a110f5b89d87d7e69d2c6984d93c"

[versions]
fabric = "0.14.9"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
