name = "Fabric Modpack 1.19"
author = "Laen111"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69f004f1d6b43d5c7ab258d400556e5854810e9c0b7c39dcfe438d841dc5a95a"

[versions]
fabric = "0.14.7"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19"]
